### PR TITLE
Fixed outofmemory error

### PR DESCRIPTION
**Pull request by OrbintSoft**
instead of loading all file in a byte buffer, I read and write only one byte per time.

### CODE REVIEW

**Comment by MahdiGhiasi** [comment]
One byte per time could make it very slow (due to high number of I/O calls), wouldn't it better if a finite amount (say, 100KB) gets loaded each time?

**Comment by OrbintSoft** [comment]
true, I made fast fix, but this can be improved.
To read 100k per time, we only need to add a check for last bytes.

**Comment by MahdiGhiasi** [comment]
I'm sorry, i just noticed that the code is now changed to buffer instead of reading byte by byte. 

May I merge the pull request?

**Comment by OrbintSoft** [comment]
I’ve tested only with few application on my device, I prefer to do some more test  on latest release before send a pull request.
The code with reading byte per byte I am sure it works, it’s slower but don’t cause OutOfMemory so it’s better than your solution.
If you want do some test on my latest release I appreciate.
Stefano.

**Comment by OrbintSoft** [comment]
I’ve tested only with few application on my device, I prefer to do some more test  on latest release before send another pull request.
The code with reading byte per byte I am sure it works, it’s slower but don’t cause OutOfMemory so it’s better than your solution.
If you want do some test on my latest release I appreciate.
Stefano.

**Comment by MahdiGhiasi** [comment]
Since you created current pull request from your master branch, it's now updated with all recent changes, including buffered reading, folder name change, and readme of your fork.

And about the changes, unfortunately I don't have my Windows phone with me at the moment, so I can't test it until at least the next week or so. I'll be happy to merge this with master as soon as I get the chance.

Thanks for keeping the project alive! 😃

**Comment by OrbintSoft** [comment]
Ok, 😁 sorry I m not a git expert lol.
I hope everything works fine…

Inviato dal mio telefono Windows 10

________________________________
Da: Mahdi Ghiasi <notifications@github.com>
Inviato: Monday, January 22, 2018 1:27:43 PM
A: MahdiGhiasi/ApplicationDataManageTool
Cc: Stefano Balzarotti; Author
Oggetto: Re: [MahdiGhiasi/ApplicationDataManageTool] Fixed outofmemory error (#1)


Since you created current pull request from your master branch, it's now updated with all recent changes, including buffered reading, folder name change, and readme of your fork.

And about the changes, unfortunately I don't have my Windows phone with me at the moment, so I can't test it until at least the next week or so. I'll be happy to merge this with master as soon as I get the chance.

Thanks for keeping the project alive! 😃

**Comment by OrbintSoft** [comment]
Can you close this pull request?
I'll create another pull request on a tag when I finish some fixs.

**Pull request closed without merging**
